# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    # Test name: test1
    # Step # | name | target | value
    # 1 | open | /login-form-main/index.html | 
    self.driver.get("http://127.0.0.1:5500/login-form-main/index.html")
    # 2 | setWindowSize | 814x816 | 
    self.driver.set_window_size(814, 816)
    # 3 | click | css=.input_group:nth-child(2) > .input_text | 
    self.driver.find_element(By.CSS_SELECTOR, ".input_group:nth-child(2) > .input_text").click()
    # 4 | type | css=.input_group:nth-child(2) > .input_text | mkfsm
    self.driver.find_element(By.CSS_SELECTOR, ".input_group:nth-child(2) > .input_text").send_keys("mkfsm")
    # 5 | click | css=.input_group:nth-child(3) > .input_text | 
    self.driver.find_element(By.CSS_SELECTOR, ".input_group:nth-child(3) > .input_text").click()
    # 6 | type | css=.input_group:nth-child(3) > .input_text | v fs vk
    self.driver.find_element(By.CSS_SELECTOR, ".input_group:nth-child(3) > .input_text").send_keys("v fs vk")
    # 7 | click | css=button | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 8 | click | css=span | 
    self.driver.find_element(By.CSS_SELECTOR, "span").click()
    # 9 | click | css=span | 
    self.driver.find_element(By.CSS_SELECTOR, "span").click()
    # 10 | click | css=span | 
    self.driver.find_element(By.CSS_SELECTOR, "span").click()
    # 11 | click | css=html | 
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
  
